default['chromium']['user'] = "deploy"
default['chromium']['expand'] = "chromium"
default['chromium']['symlink'] = "chromium"
default['chromium']['chrome'] = "chrome"
default['chromium']['chrome_sandbox'] = "chrome_sandbox"
default['chromium']['location'] = "https://www.googleapis.com/download/storage/v1/b/chromium-browser-snapshots/o/Linux%2F308448%2Fchrome-linux.zip?generation=1418688583562000&alt=media"
